version: '3.4'

services:
  SqlServerDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123videninSERG13
    networks:
      - eocnetwork
  eoc_2_0:
    image: pud
    build:
      context: ./EOC_2_0
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - SqlServerDb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - eocnetwork
    restart: on-failure

networks:
  eocnetwork:
