version: '3.4'

services:
  eoc_2_0:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/dev-cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ./data-protection-keys:/root/.aspnet/DataProtection-Keys
      - ./certificates/dev-cert.pfx:/root/.aspnet/https/dev-cert.pfx:ro
